version: '0.1'

services:
  db:
    image: mysql:8.4.3
    container_name: mysql_db
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/init-sql:/docker-entrypoint-initdb.d
    - ./docker/db/my.cnf:/etc/my.cnf
    ports:
      - '3306:3306'
    tty: true